/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadordecatracas.gui;

import gerenciadordecatracas.gerenciamento.CatracaVirtual;
import gerenciadordecatracas.gerenciamento.Historico;
import gerenciadordecatracas.gerenciamento.Utilitario;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author Gamarra
 */
public class MenuCatracas extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameCatracas
     */
    public MenuCatracas() {
        initComponents();
    }
    
    //Classes utilizadas
    CatracaVirtual catraca = new CatracaVirtual();
    Utilitario util = new Utilitario();
    Historico historico = new Historico();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameEntrada = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        campoConsultaEntrada = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        btnCancelarEntrada = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        frameSaida = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        campoConsultaSaida = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnCancelarSaida = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        frameAutomatica = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        campoConsultaAuto = new javax.swing.JTextField();
        btnCancelarAuto = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dialogEntradas = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPanelEntradas = new javax.swing.JTextPane();
        btnFecharEntradas = new javax.swing.JButton();
        dialogSaidas = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPanelSaidas = new javax.swing.JTextPane();
        btnFecharSaidas = new javax.swing.JButton();
        dialogMensagemEntrada = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPanelDialogEntrada = new javax.swing.JTextPane();
        btnFecharMsgEntrada = new javax.swing.JButton();
        dialogMensagemSaida = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textPanelDialogSaida = new javax.swing.JTextPane();
        btnFecharMsgSaida = new javax.swing.JButton();
        dialogMensagemAutomatica = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textPanelAutomatica = new javax.swing.JTextPane();
        btnFecharMsgAutomatica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEntrada = new javax.swing.JButton();
        btnVoltarCatracas = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        btnAutomatica = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        frameEntrada.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameEntrada.setTitle("PROJETO FINAL - ENTRADA");
        frameEntrada.setForeground(java.awt.Color.white);
        frameEntrada.setMinimumSize(new java.awt.Dimension(315, 280));
        frameEntrada.setPreferredSize(new java.awt.Dimension(315, 280));
        frameEntrada.setResizable(false);
        frameEntrada.setLocationRelativeTo(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("CÓDIGO:");

        campoConsultaEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoConsultaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsultaEntradaActionPerformed(evt);
            }
        });
        campoConsultaEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoConsultaEntradaKeyPressed(evt);
            }
        });

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnCancelarEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelarEntrada.setText("CANCELAR");
        btnCancelarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEntradaActionPerformed(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadordecatracas/gui/catraca.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ENTRADA");

        javax.swing.GroupLayout frameEntradaLayout = new javax.swing.GroupLayout(frameEntrada.getContentPane());
        frameEntrada.getContentPane().setLayout(frameEntradaLayout);
        frameEntradaLayout.setHorizontalGroup(
            frameEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frameEntradaLayout.createSequentialGroup()
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameEntradaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoConsultaEntrada)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameEntradaLayout.setVerticalGroup(
            frameEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConsultaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(btnCancelarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameEntrada.getAccessibleContext().setAccessibleDescription("");

        frameSaida.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameSaida.setTitle("PROJETO FINAL - SAÍDA");
        frameSaida.setForeground(java.awt.Color.white);
        frameSaida.setMinimumSize(new java.awt.Dimension(315, 280));
        frameSaida.setLocationRelativeTo(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("CÓDIGO:");

        campoConsultaSaida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoConsultaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsultaSaidaActionPerformed(evt);
            }
        });
        campoConsultaSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoConsultaSaidaKeyPressed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setMaximumSize(new java.awt.Dimension(252, 81));
        btnSair.setMinimumSize(new java.awt.Dimension(252, 81));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelarSaida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelarSaida.setText("CANCELAR");
        btnCancelarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSaidaActionPerformed(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadordecatracas/gui/catraca.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("SAÍDA");

        javax.swing.GroupLayout frameSaidaLayout = new javax.swing.GroupLayout(frameSaida.getContentPane());
        frameSaida.getContentPane().setLayout(frameSaidaLayout);
        frameSaidaLayout.setHorizontalGroup(
            frameSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frameSaidaLayout.createSequentialGroup()
                        .addGroup(frameSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frameSaidaLayout.createSequentialGroup()
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frameSaidaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoConsultaSaida)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frameSaidaLayout.setVerticalGroup(
            frameSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(11, 11, 11)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoConsultaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarSaida)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameAutomatica.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameAutomatica.setTitle("PROJETO FINAL - ENTRADA/SAIDA");
        frameAutomatica.setForeground(java.awt.Color.white);
        frameAutomatica.setMinimumSize(new java.awt.Dimension(315, 280));
        frameAutomatica.setLocationRelativeTo(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("CÓDIGO:");

        campoConsultaAuto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoConsultaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoConsultaAutoActionPerformed(evt);
            }
        });
        campoConsultaAuto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoConsultaAutoKeyPressed(evt);
            }
        });

        btnCancelarAuto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelarAuto.setText("CANCELAR");
        btnCancelarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAutoActionPerformed(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadordecatracas/gui/catraca.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("ENTRADA/SAÍDA");

        javax.swing.GroupLayout frameAutomaticaLayout = new javax.swing.GroupLayout(frameAutomatica.getContentPane());
        frameAutomatica.getContentPane().setLayout(frameAutomaticaLayout);
        frameAutomaticaLayout.setHorizontalGroup(
            frameAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAutomaticaLayout.createSequentialGroup()
                .addGroup(frameAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAutomaticaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(frameAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frameAutomaticaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoConsultaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(frameAutomaticaLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnCancelarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameAutomaticaLayout.setVerticalGroup(
            frameAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameAutomaticaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addGap(4, 4, 4)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoConsultaAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarAuto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogEntradas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogEntradas.setTitle("HISTÓRICO");
        dialogEntradas.setAlwaysOnTop(true);
        dialogEntradas.setBackground(new java.awt.Color(255, 255, 255));
        dialogEntradas.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogEntradas.setResizable(false);
        dialogEntradas.setLocationRelativeTo(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HISTÓRICO ENTRADA");

        textPanelEntradas.setEditable(false);
        jScrollPane1.setViewportView(textPanelEntradas);

        btnFecharEntradas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFecharEntradas.setText("FECHAR");
        btnFecharEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharEntradasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogEntradasLayout = new javax.swing.GroupLayout(dialogEntradas.getContentPane());
        dialogEntradas.getContentPane().setLayout(dialogEntradasLayout);
        dialogEntradasLayout.setHorizontalGroup(
            dialogEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnFecharEntradas)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        dialogEntradasLayout.setVerticalGroup(
            dialogEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEntradasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFecharEntradas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogSaidas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogSaidas.setTitle("HISTÓRICO");
        dialogSaidas.setAlwaysOnTop(true);
        dialogSaidas.setBackground(new java.awt.Color(255, 255, 255));
        dialogSaidas.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogSaidas.setResizable(false);
        dialogSaidas.setLocationRelativeTo(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HISTÓRICO SAÍDA");

        textPanelSaidas.setEditable(false);
        jScrollPane2.setViewportView(textPanelSaidas);

        btnFecharSaidas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFecharSaidas.setText("FECHAR");
        btnFecharSaidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharSaidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogSaidasLayout = new javax.swing.GroupLayout(dialogSaidas.getContentPane());
        dialogSaidas.getContentPane().setLayout(dialogSaidasLayout);
        dialogSaidasLayout.setHorizontalGroup(
            dialogSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSaidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnFecharSaidas)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        dialogSaidasLayout.setVerticalGroup(
            dialogSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSaidasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFecharSaidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogMensagemEntrada.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogMensagemEntrada.setTitle("ENTRADA");
        dialogMensagemEntrada.setAlwaysOnTop(true);
        dialogMensagemEntrada.setBackground(new java.awt.Color(255, 255, 255));
        dialogMensagemEntrada.setMinimumSize(new java.awt.Dimension(450, 220));
        dialogMensagemEntrada.setResizable(false);
        dialogMensagemEntrada.setLocationRelativeTo(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ENTRADA");

        textPanelDialogEntrada.setEditable(false);
        textPanelDialogEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textPanelDialogEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPanelDialogEntradaKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(textPanelDialogEntrada);

        btnFecharMsgEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFecharMsgEntrada.setText("FECHAR");
        btnFecharMsgEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharMsgEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogMensagemEntradaLayout = new javax.swing.GroupLayout(dialogMensagemEntrada.getContentPane());
        dialogMensagemEntrada.getContentPane().setLayout(dialogMensagemEntradaLayout);
        dialogMensagemEntradaLayout.setHorizontalGroup(
            dialogMensagemEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMensagemEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogMensagemEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFecharMsgEntrada, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogMensagemEntradaLayout.setVerticalGroup(
            dialogMensagemEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMensagemEntradaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFecharMsgEntrada)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        dialogMensagemSaida.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogMensagemSaida.setTitle("ENTRADA");
        dialogMensagemSaida.setAlwaysOnTop(true);
        dialogMensagemSaida.setBackground(new java.awt.Color(255, 255, 255));
        dialogMensagemSaida.setMinimumSize(new java.awt.Dimension(450, 220));
        dialogMensagemSaida.setResizable(false);
        dialogMensagemSaida.setLocationRelativeTo(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SAÍDA");

        textPanelDialogSaida.setEditable(false);
        textPanelDialogSaida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textPanelDialogSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPanelDialogSaidaKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(textPanelDialogSaida);

        btnFecharMsgSaida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFecharMsgSaida.setText("FECHAR");
        btnFecharMsgSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharMsgSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogMensagemSaidaLayout = new javax.swing.GroupLayout(dialogMensagemSaida.getContentPane());
        dialogMensagemSaida.getContentPane().setLayout(dialogMensagemSaidaLayout);
        dialogMensagemSaidaLayout.setHorizontalGroup(
            dialogMensagemSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMensagemSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogMensagemSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFecharMsgSaida, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogMensagemSaidaLayout.setVerticalGroup(
            dialogMensagemSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMensagemSaidaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFecharMsgSaida)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        dialogMensagemAutomatica.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogMensagemAutomatica.setTitle("ENTRADA");
        dialogMensagemAutomatica.setAlwaysOnTop(true);
        dialogMensagemAutomatica.setBackground(new java.awt.Color(255, 255, 255));
        dialogMensagemAutomatica.setMinimumSize(new java.awt.Dimension(450, 220));
        dialogMensagemAutomatica.setResizable(false);
        dialogMensagemAutomatica.setLocationRelativeTo(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ENTRADA/SAÍDA");

        textPanelAutomatica.setEditable(false);
        textPanelAutomatica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textPanelAutomatica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textPanelAutomaticaKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(textPanelAutomatica);

        btnFecharMsgAutomatica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFecharMsgAutomatica.setText("FECHAR");
        btnFecharMsgAutomatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharMsgAutomaticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogMensagemAutomaticaLayout = new javax.swing.GroupLayout(dialogMensagemAutomatica.getContentPane());
        dialogMensagemAutomatica.getContentPane().setLayout(dialogMensagemAutomaticaLayout);
        dialogMensagemAutomaticaLayout.setHorizontalGroup(
            dialogMensagemAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMensagemAutomaticaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogMensagemAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFecharMsgAutomatica, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogMensagemAutomaticaLayout.setVerticalGroup(
            dialogMensagemAutomaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogMensagemAutomaticaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFecharMsgAutomatica)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CATRACAS");
        setMinimumSize(new java.awt.Dimension(340, 360));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciadordecatracas/gui/catraca.png"))); // NOI18N

        btnEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEntrada.setText("ENTRADA");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnVoltarCatracas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltarCatracas.setText("VOLTAR");
        btnVoltarCatracas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCatracasActionPerformed(evt);
            }
        });

        btnSaida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSaida.setText("SAÍDA");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        btnAutomatica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAutomatica.setText("CATRACA AUTOMÁTICA");
        btnAutomatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticaActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntrada, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAutomatica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(btnVoltarCatracas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutomatica, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltarCatracas, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getCampoConsultaEntrada() {
        return campoConsultaEntrada;
    }

    public void setCampoConsultaEntrada(JTextField campoConsultaEntrada) {
        this.campoConsultaEntrada = campoConsultaEntrada;
    }

    public JFrame getFrameAutomatica() {
        return frameAutomatica;
    }

    public void setFrameAutomatica(JFrame frameAutomatica) {
        this.frameAutomatica = frameAutomatica;
    }
    
    public JTextField getCampoConsultaAuto() {
        return campoConsultaAuto;
    }

    public void setCampoConsultaAuto(JTextField campoConsultaAuto) {
        this.campoConsultaAuto = campoConsultaAuto;
    }

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        frameSaida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        frameEntrada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        textPanelDialogEntrada.setText(catraca.entradaCatracaVirtual(this));
        util.limparFrame(frameEntrada);
        if(!textPanelDialogEntrada.getText().equals("")){
            dialogMensagemEntrada.setVisible(true);
            util.limparFrame(frameEntrada);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCancelarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEntradaActionPerformed
        frameEntrada.dispose();
        new MenuCatracas().setVisible(true);
    }//GEN-LAST:event_btnCancelarEntradaActionPerformed

    private void campoConsultaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConsultaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConsultaEntradaActionPerformed

    private void btnVoltarCatracasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCatracasActionPerformed
        MenuCatracas.this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVoltarCatracasActionPerformed

    private void campoConsultaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConsultaSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConsultaSaidaActionPerformed

    public JTextField getCampoConsultaSaida() {
        return campoConsultaSaida;
    }

    public void setCampoConsultaSaida(JTextField campoConsultaSaida) {
        this.campoConsultaSaida = campoConsultaSaida;
    }

    public JFrame getFrameEntrada() {
        return frameEntrada;
    }

    public void setFrameEntrada(JFrame frameEntrada) {
        this.frameEntrada = frameEntrada;
    }

    public JFrame getFrameSaida() {
        return frameSaida;
    }

    public void setFrameSaida(JFrame frameSaida) {
        this.frameSaida = frameSaida;
    }

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        textPanelDialogSaida.setText(catraca.saidaCatracaVirtual(this));
        util.limparFrame(frameSaida);
        if(!textPanelDialogSaida.getText().equals("")){
            dialogMensagemSaida.setVisible(true);
            util.limparFrame(frameSaida);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCancelarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSaidaActionPerformed
        frameSaida.dispose();
        new MenuCatracas().setVisible(true);
    }//GEN-LAST:event_btnCancelarSaidaActionPerformed

    private void campoConsultaEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoConsultaEntradaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {                    
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_campoConsultaEntradaKeyPressed

    private void campoConsultaSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoConsultaSaidaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {                    
            btnSair.doClick();
        }
    }//GEN-LAST:event_campoConsultaSaidaKeyPressed

    private void btnAutomaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticaActionPerformed
        frameAutomatica.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAutomaticaActionPerformed

    private void campoConsultaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConsultaAutoActionPerformed
        textPanelAutomatica.setText(catraca.catracaVirtualAutomatica(this));
        util.limparFrame(frameAutomatica);
        if(!textPanelAutomatica.getText().equals("")){
            dialogMensagemAutomatica.setVisible(true);
            util.limparFrame(frameAutomatica);
        }
    }//GEN-LAST:event_campoConsultaAutoActionPerformed

    private void campoConsultaAutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoConsultaAutoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConsultaAutoKeyPressed

    private void btnCancelarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAutoActionPerformed
        frameAutomatica.dispose();
        new MenuCatracas().setVisible(true);
    }//GEN-LAST:event_btnCancelarAutoActionPerformed

    private void btnFecharEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharEntradasActionPerformed
        dialogEntradas.dispose();
    }//GEN-LAST:event_btnFecharEntradasActionPerformed

    private void btnFecharSaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharSaidasActionPerformed
        dialogSaidas.dispose();
    }//GEN-LAST:event_btnFecharSaidasActionPerformed

    private void btnFecharMsgEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharMsgEntradaActionPerformed
        dialogMensagemEntrada.dispose();
    }//GEN-LAST:event_btnFecharMsgEntradaActionPerformed

    private void btnFecharMsgSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharMsgSaidaActionPerformed
        dialogMensagemSaida.dispose();
    }//GEN-LAST:event_btnFecharMsgSaidaActionPerformed

    private void btnFecharMsgAutomaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharMsgAutomaticaActionPerformed
        dialogMensagemAutomatica.dispose();
    }//GEN-LAST:event_btnFecharMsgAutomaticaActionPerformed

    private void textPanelDialogEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPanelDialogEntradaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {                    
            btnFecharMsgEntrada.doClick();
        }
    }//GEN-LAST:event_textPanelDialogEntradaKeyPressed

    private void textPanelDialogSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPanelDialogSaidaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {                    
            btnFecharMsgSaida.doClick();
        }
    }//GEN-LAST:event_textPanelDialogSaidaKeyPressed

    private void textPanelAutomaticaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPanelAutomaticaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {                    
            btnFecharMsgAutomatica.doClick();
        }
    }//GEN-LAST:event_textPanelAutomaticaKeyPressed

    public JTextField getCampoConsulta() {
        return campoConsultaEntrada;
    }

    public void setCampoConsulta(JTextField campoConsulta) {
        this.campoConsultaEntrada = campoConsulta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCatracas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCatracas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCatracas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCatracas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCatracas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomatica;
    private javax.swing.JButton btnCancelarAuto;
    private javax.swing.JButton btnCancelarEntrada;
    private javax.swing.JButton btnCancelarSaida;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnFecharEntradas;
    private javax.swing.JButton btnFecharMsgAutomatica;
    private javax.swing.JButton btnFecharMsgEntrada;
    private javax.swing.JButton btnFecharMsgSaida;
    private javax.swing.JButton btnFecharSaidas;
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltarCatracas;
    private javax.swing.JTextField campoConsultaAuto;
    private javax.swing.JTextField campoConsultaEntrada;
    private javax.swing.JTextField campoConsultaSaida;
    private javax.swing.JDialog dialogEntradas;
    private javax.swing.JDialog dialogMensagemAutomatica;
    private javax.swing.JDialog dialogMensagemEntrada;
    private javax.swing.JDialog dialogMensagemSaida;
    private javax.swing.JDialog dialogSaidas;
    private javax.swing.JFrame frameAutomatica;
    private javax.swing.JFrame frameEntrada;
    private javax.swing.JFrame frameSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane textPanelAutomatica;
    private javax.swing.JTextPane textPanelDialogEntrada;
    private javax.swing.JTextPane textPanelDialogSaida;
    private javax.swing.JTextPane textPanelEntradas;
    private javax.swing.JTextPane textPanelSaidas;
    // End of variables declaration//GEN-END:variables
}
