package view;

import controller.ControllerConfig;
import controller.ControllerEntradaSaida;
import controller.ControllerHistorico;
import java.awt.EventQueue;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author cassio
 */
public class ViewSistema extends javax.swing.JFrame {
    private static final DateFormat FORMATO = new SimpleDateFormat("HH:mm:ss");
    /**
     * Creates new form ViewPainelAdministrador
     */
    public ViewSistema() {
        initComponents();
        // Iniciamos a thread do relógio. Tornei uma deamon thread para que seja
        // automaticamente finalizada caso a aplicação feche.
        Thread clockThread = new Thread(new ViewSistema.ClockRunnable(), "Clock thread");
        clockThread.setDaemon(true);
        clockThread.start(); 
    }
    //Hora do sistema
    
    /**
     * Método para atualizar a hora no formulário. Não é thread-safe, portanto,
     * @param date
     */
    public void setHora(Date date) {
        lblHora.setText(FORMATO.format(date));
    }
    
    /**
     * Runnable que contém o código que atuará na thread. Chamando o método setHora
     */
    private class ClockRunnable implements Runnable {
        public void run() {
            try {
                while (true) {
                    // Aqui chamamos o setHora através da EventQueue da AWT.
                    // Conforme dito, isso garante Thread safety para o Swing.
                    EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            // Só podemos chamar setHora diretamente dessa
                            // forma, pois esse Runnable é uma InnerClass não
                            // estática.
                            setHora(new Date());
                        }
                    });
                    // Fazemos nossa thread dormir por um segundo, liberando o
                    // processador para outras threads processarem.
                    Thread.sleep(1000);
                }
            }
            catch (InterruptedException e) {
            }
        }
    }
    
    //Getter
    
    public JLabel getLblHoraEntradaCupomSaida() {
        return lblHoraEntradaCupomSaida;
    }

    public JLabel getLblHoraEntradaCupom() {
        return lblHoraEntradaCupom;
    }

    public JLabel getLblHoraSaidaCupomSaida() {
        return lblHoraSaidaCupomSaida;
    }

    public JLabel getLblPlacaCupom() {
        return lblPlacaCupom;
    }

    public JLabel getLblPlacaCupomSaida() {    
        return lblPlacaCupomSaida;
    }

    public JLabel getLblHora() {
        return lblHora;
    }
    
    public JTable getTabelaHistorico() {
        return tabelaHistorico;
    }

    public JTextField getFieldPlacaEntrada() {
        return fieldPlaca;
    }

    public JComboBox<String> getFieldTipoVeiculo() {
        return comboTipoVeiculo;
    }
    
    
    public JButton getBtnSalvarConfig() {
        return btnSalvarConfig;
    }
    
    public JTextField getFieldNomeGaragem() {
        return fieldNomeGaragem;
    }
 
    public JTextField getFieldQtdVagas() {    
        return fieldQtdVagas;
    }

    public JLabel getLabelNomeGaragem() {
        return labelNomeGaragem;
    }

    public JFrame getViewEntrada() {
        return ViewGerenciamento;
    }

    public JTable getTabelaVagas() {
        return tabelaVagas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewGerenciamento = new javax.swing.JFrame();
        panelEntrada = new javax.swing.JPanel();
        fieldPlaca = new javax.swing.JTextField();
        comboTipoVeiculo = new javax.swing.JComboBox<>();
        btnEntrada = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVagas = new javax.swing.JTable();
        btnSaida = new javax.swing.JButton();
        dialogCupomEntrada = new javax.swing.JDialog();
        panelCupomEntrada = new javax.swing.JPanel();
        lblNomeGaragemCupom = new javax.swing.JLabel();
        lblPlacaCupom = new javax.swing.JLabel();
        lblHoraEntradaCupom = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dialogCupomSaida = new javax.swing.JDialog();
        panelCupom1 = new javax.swing.JPanel();
        lblNomeGaragemCupom1 = new javax.swing.JLabel();
        lblPlacaCupomSaida = new javax.swing.JLabel();
        lblHoraEntradaCupomSaida = new javax.swing.JLabel();
        lblHoraSaidaCupomSaida = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ViewPainelAdm = new javax.swing.JTabbedPane();
        GuiaPrincipal = new javax.swing.JPanel();
        btnGerenciar = new javax.swing.JButton();
        labelNomeGaragem = new javax.swing.JLabel();
        GuiaHistorico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHistorico = new javax.swing.JTable();
        GuiaConfig = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalvarConfig = new javax.swing.JButton();
        fieldQtdVagas = new javax.swing.JTextField();
        fieldNomeGaragem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        GuiaSobre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        ViewGerenciamento.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ViewGerenciamento.setMinimumSize(new java.awt.Dimension(580, 480));

        panelEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GERENCIADOR - ENTRADA E SAÍDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        fieldPlaca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PLACA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        comboTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Carro", "Caminhão", "Moto", "Ônibus" }));
        comboTipoVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        comboTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoVeiculoActionPerformed(evt);
            }
        });

        btnEntrada.setText("ENTRADA");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VAGAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tabelaVagas.setBackground(new java.awt.Color(0, 102, 0));
        tabelaVagas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaVagas.setForeground(new java.awt.Color(255, 255, 255));
        tabelaVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VAGA", "PLACA", "TIPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVagasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaVagas);

        btnSaida.setText("SAÍDA");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEntradaLayout = new javax.swing.GroupLayout(panelEntrada);
        panelEntrada.setLayout(panelEntradaLayout);
        panelEntradaLayout.setHorizontalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldPlaca)
                    .addComponent(comboTipoVeiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEntradaLayout.createSequentialGroup()
                        .addComponent(btnEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEntradaLayout.setVerticalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrada)
                    .addComponent(btnVoltar)
                    .addComponent(btnSaida))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ViewGerenciamentoLayout = new javax.swing.GroupLayout(ViewGerenciamento.getContentPane());
        ViewGerenciamento.getContentPane().setLayout(ViewGerenciamentoLayout);
        ViewGerenciamentoLayout.setHorizontalGroup(
            ViewGerenciamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewGerenciamentoLayout.createSequentialGroup()
                .addComponent(panelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ViewGerenciamentoLayout.setVerticalGroup(
            ViewGerenciamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogCupomEntrada.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogCupomEntrada.setMaximumSize(new java.awt.Dimension(460, 420));
        dialogCupomEntrada.setMinimumSize(new java.awt.Dimension(460, 420));
        dialogCupomEntrada.setPreferredSize(new java.awt.Dimension(460, 420));

        panelCupomEntrada.setBackground(new java.awt.Color(253, 245, 171));
        panelCupomEntrada.setForeground(new java.awt.Color(253, 245, 171));
        panelCupomEntrada.setToolTipText("");

        lblNomeGaragemCupom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeGaragemCupom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPlacaCupom.setBackground(new java.awt.Color(253, 245, 171));
        lblPlacaCupom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlacaCupom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlacaCupom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PLACA:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblHoraEntradaCupom.setBackground(new java.awt.Color(253, 245, 171));
        lblHoraEntradaCupom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraEntradaCupom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoraEntradaCupom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENTRADA: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout panelCupomEntradaLayout = new javax.swing.GroupLayout(panelCupomEntrada);
        panelCupomEntrada.setLayout(panelCupomEntradaLayout);
        panelCupomEntradaLayout.setHorizontalGroup(
            panelCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCupomEntradaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNomeGaragemCupom, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(lblPlacaCupom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHoraEntradaCupom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelCupomEntradaLayout.setVerticalGroup(
            panelCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
            .addGroup(panelCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCupomEntradaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNomeGaragemCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(lblPlacaCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblHoraEntradaCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dialogCupomEntrada.setLocationRelativeTo(null);

        javax.swing.GroupLayout dialogCupomEntradaLayout = new javax.swing.GroupLayout(dialogCupomEntrada.getContentPane());
        dialogCupomEntrada.getContentPane().setLayout(dialogCupomEntradaLayout);
        dialogCupomEntradaLayout.setHorizontalGroup(
            dialogCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCupomEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelCupomEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogCupomEntradaLayout.setVerticalGroup(
            dialogCupomEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCupomEntradaLayout.createSequentialGroup()
                .addComponent(panelCupomEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        dialogCupomSaida.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogCupomSaida.setMaximumSize(new java.awt.Dimension(460, 420));
        dialogCupomSaida.setMinimumSize(new java.awt.Dimension(460, 420));
        dialogCupomSaida.setPreferredSize(new java.awt.Dimension(460, 420));

        panelCupom1.setBackground(new java.awt.Color(253, 245, 171));
        panelCupom1.setForeground(new java.awt.Color(253, 245, 171));
        panelCupom1.setToolTipText("");

        lblNomeGaragemCupom1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeGaragemCupom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPlacaCupomSaida.setBackground(new java.awt.Color(253, 245, 171));
        lblPlacaCupomSaida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlacaCupomSaida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlacaCupomSaida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PLACA:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblHoraEntradaCupomSaida.setBackground(new java.awt.Color(253, 245, 171));
        lblHoraEntradaCupomSaida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraEntradaCupomSaida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HORA ENTRADA: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblHoraSaidaCupomSaida.setBackground(new java.awt.Color(253, 245, 171));
        lblHoraSaidaCupomSaida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoraSaidaCupomSaida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HORA SAÍDA: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout panelCupom1Layout = new javax.swing.GroupLayout(panelCupom1);
        panelCupom1.setLayout(panelCupom1Layout);
        panelCupom1Layout.setHorizontalGroup(
            panelCupom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelCupom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCupom1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelCupom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNomeGaragemCupom1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(lblPlacaCupomSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHoraEntradaCupomSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHoraSaidaCupomSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelCupom1Layout.setVerticalGroup(
            panelCupom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
            .addGroup(panelCupom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCupom1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNomeGaragemCupom1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(lblPlacaCupomSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblHoraEntradaCupomSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblHoraSaidaCupomSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dialogCupomSaida.setLocationRelativeTo(null);

        javax.swing.GroupLayout dialogCupomSaidaLayout = new javax.swing.GroupLayout(dialogCupomSaida.getContentPane());
        dialogCupomSaida.getContentPane().setLayout(dialogCupomSaidaLayout);
        dialogCupomSaidaLayout.setHorizontalGroup(
            dialogCupomSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCupomSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogCupomSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelCupom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        dialogCupomSaidaLayout.setVerticalGroup(
            dialogCupomSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCupomSaidaLayout.createSequentialGroup()
                .addComponent(panelCupom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 500));
        setMinimumSize(new java.awt.Dimension(1024, 500));

        ViewPainelAdm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        GuiaPrincipal.setBackground(new java.awt.Color(1, 96, 173));
        GuiaPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        btnGerenciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGerenciar.png"))); // NOI18N
        btnGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarActionPerformed(evt);
            }
        });

        labelNomeGaragem.setBackground(new java.awt.Color(255, 255, 255));
        labelNomeGaragem.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        labelNomeGaragem.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeGaragem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout GuiaPrincipalLayout = new javax.swing.GroupLayout(GuiaPrincipal);
        GuiaPrincipal.setLayout(GuiaPrincipalLayout);
        GuiaPrincipalLayout.setHorizontalGroup(
            GuiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuiaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GuiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNomeGaragem, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
                    .addComponent(btnGerenciar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        GuiaPrincipalLayout.setVerticalGroup(
            GuiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuiaPrincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelNomeGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnGerenciar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        ViewPainelAdm.addTab("ESTACIONAMENTO", GuiaPrincipal);

        GuiaHistorico.setBackground(new java.awt.Color(1, 96, 173));

        tabelaHistorico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "VAGA", "DATA ENTRADA", "HORA ENTRADA", "DATA SAÍDA", "HORA SAÍDA", "TIPO VEÍCULO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaHistorico.setEnabled(false);
        jScrollPane1.setViewportView(tabelaHistorico);

        javax.swing.GroupLayout GuiaHistoricoLayout = new javax.swing.GroupLayout(GuiaHistorico);
        GuiaHistorico.setLayout(GuiaHistoricoLayout);
        GuiaHistoricoLayout.setHorizontalGroup(
            GuiaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
        );
        GuiaHistoricoLayout.setVerticalGroup(
            GuiaHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        ViewPainelAdm.addTab("HISTÓRICO", GuiaHistorico);

        GuiaConfig.setBackground(new java.awt.Color(1, 96, 173));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config.png"))); // NOI18N

        btnSalvarConfig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvarConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSalvar.png"))); // NOI18N
        btnSalvarConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarConfigActionPerformed(evt);
            }
        });

        fieldQtdVagas.setBackground(new java.awt.Color(189, 219, 255));
        fieldQtdVagas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldQtdVagas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° DE VAGAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        fieldQtdVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQtdVagasActionPerformed(evt);
            }
        });

        fieldNomeGaragem.setBackground(new java.awt.Color(189, 219, 255));
        fieldNomeGaragem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fieldNomeGaragem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOME DA GARAGEM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        fieldNomeGaragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeGaragemActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config.png"))); // NOI18N

        javax.swing.GroupLayout GuiaConfigLayout = new javax.swing.GroupLayout(GuiaConfig);
        GuiaConfig.setLayout(GuiaConfigLayout);
        GuiaConfigLayout.setHorizontalGroup(
            GuiaConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuiaConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GuiaConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuiaConfigLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldQtdVagas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuiaConfigLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNomeGaragem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuiaConfigLayout.createSequentialGroup()
                        .addGap(0, 1066, Short.MAX_VALUE)
                        .addComponent(btnSalvarConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        GuiaConfigLayout.setVerticalGroup(
            GuiaConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuiaConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GuiaConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldNomeGaragem)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GuiaConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldQtdVagas)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        ViewPainelAdm.addTab("CONFIGURAÇÕES", GuiaConfig);

        javax.swing.GroupLayout GuiaSobreLayout = new javax.swing.GroupLayout(GuiaSobre);
        GuiaSobre.setLayout(GuiaSobreLayout);
        GuiaSobreLayout.setHorizontalGroup(
            GuiaSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1228, Short.MAX_VALUE)
        );
        GuiaSobreLayout.setVerticalGroup(
            GuiaSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        ViewPainelAdm.addTab("SOBRE", GuiaSobre);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 96, 173));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sistema.png"))); // NOI18N

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHora.setForeground(new java.awt.Color(1, 96, 173));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewPainelAdm)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewPainelAdm))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoVeiculoActionPerformed

    private void fieldQtdVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQtdVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQtdVagasActionPerformed

    private void btnSalvarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarConfigActionPerformed
        // TODO add your handling code here:
       ControllerConfig configurar = new ControllerConfig();
       configurar.configurarGaragem(fieldNomeGaragem.getText(), Integer.parseInt(fieldQtdVagas.getText()));
       configurar.buscarConfig(this);
    }//GEN-LAST:event_btnSalvarConfigActionPerformed

    private void btnGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarActionPerformed
            // TODO add your handling code here:
        ViewGerenciamento.setLocationRelativeTo(null);
        ViewGerenciamento.setVisible(true);
    }//GEN-LAST:event_btnGerenciarActionPerformed

    private void fieldNomeGaragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeGaragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeGaragemActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        ViewGerenciamento.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        // TODO add your handling code here:
        ControllerEntradaSaida entradaSaida = new ControllerEntradaSaida();
        String msg = "";
        msg = entradaSaida.entradaGaragem(this);
        
        if(!msg.equals("")){
            lblNomeGaragemCupom.setText(labelNomeGaragem.getText());
            dialogCupomEntrada.setVisible(true);
            fieldPlaca.setText("");
            comboTipoVeiculo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        // TODO add your handling code here:
        ControllerEntradaSaida entradaSaida = new ControllerEntradaSaida();
        ControllerHistorico historico = new ControllerHistorico();
        String msg = "";
        msg = entradaSaida.saidaGaragem(this);
        
        if(!msg.equals("")){
            lblNomeGaragemCupom1.setText(labelNomeGaragem.getText());
            dialogCupomSaida.setVisible(true);
            fieldPlaca.setText("");
            comboTipoVeiculo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void tabelaVagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVagasMouseClicked
        // TODO add your handling code here:
        String placa, tipo;
        try {
            placa = tabelaVagas.getValueAt(tabelaVagas.getSelectedRow(), 1).toString();
            tipo = tabelaVagas.getValueAt(tabelaVagas.getSelectedRow(), 2).toString();
            
            if(!placa.equals("LIVRE")){
                fieldPlaca.setText(placa);
                comboTipoVeiculo.setSelectedItem(tipo);
            }
            else{
                fieldPlaca.setText("");
                comboTipoVeiculo.setSelectedIndex(0);
            }
        } 
        catch (Exception e) {
            fieldPlaca.setText("");
            comboTipoVeiculo.setSelectedItem("Selecione");
        }
    }//GEN-LAST:event_tabelaVagasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dialogCupomEntrada.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dialogCupomSaida.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GuiaConfig;
    private javax.swing.JPanel GuiaHistorico;
    private javax.swing.JPanel GuiaPrincipal;
    private javax.swing.JPanel GuiaSobre;
    private javax.swing.JFrame ViewGerenciamento;
    private javax.swing.JTabbedPane ViewPainelAdm;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnGerenciar;
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton btnSalvarConfig;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboTipoVeiculo;
    private javax.swing.JDialog dialogCupomEntrada;
    private javax.swing.JDialog dialogCupomSaida;
    private javax.swing.JTextField fieldNomeGaragem;
    private javax.swing.JTextField fieldPlaca;
    private javax.swing.JTextField fieldQtdVagas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNomeGaragem;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHoraEntradaCupom;
    private javax.swing.JLabel lblHoraEntradaCupomSaida;
    private javax.swing.JLabel lblHoraSaidaCupomSaida;
    private javax.swing.JLabel lblNomeGaragemCupom;
    private javax.swing.JLabel lblNomeGaragemCupom1;
    private javax.swing.JLabel lblPlacaCupom;
    private javax.swing.JLabel lblPlacaCupomSaida;
    private javax.swing.JPanel panelCupom1;
    private javax.swing.JPanel panelCupomEntrada;
    private javax.swing.JPanel panelEntrada;
    private javax.swing.JTable tabelaHistorico;
    private javax.swing.JTable tabelaVagas;
    // End of variables declaration//GEN-END:variables
}
